ignore error when trying to delete a non-exist remote branch (vibe-kanban 5c079491)
when deleting remote branch, if it doesn't exist, we can safely ignore the error and considered it success.

example error:

## Error Type

Console Error

## Error Message

Pushing to https://github.com/m0o0scar/git-web.git

error: unable to delete 'vk/f716-in-workspace-cha': remote ref does not exist

error: failed to push some refs to 'https://github.com/m0o0scar/git-web.git'

    at useGitAction.useMutation [as mutationFn] (src/hooks/use-git.ts:410:15)

## Code Frame

  408 |       if (!res.ok) {

  409 |         const error = await res.json();

> 410 |         throw new Error(error.error || 'Failed to execute action');

      |               ^

  411 |       }

  412 |       return res.json();

  413 |     },

Next.js version: 16.1.6 (Webpack)